"""add columns

Revision ID: f67eaa69e91f
Revises: e08fc0218f8b
Create Date: 2024-04-14 21:07:50.074349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f67eaa69e91f'
down_revision = 'e08fc0218f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('photo_url', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_column('photo_url')
        batch_op.drop_column('breed')

    # ### end Alembic commands ###
